import TaskList from "../../components/taskList/TaskList";

const TaskData = [
    {
      groupTitle: "NPO 01 Tasks",
      tasks: [
        {
          taskTitle: "Schedule Meeting with Mediator",
          time: "Today 11:00 AM",
          taskNumber: 2,
          totalEvents: 5,
          priority: "High",
          priorityLabel: "High",
          completed: false,
        },
        {
          taskTitle: "Translation Feedback from Client",
          time: "Today 08:00 AM",
          taskNumber: 2,
          totalEvents: 5,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: true,
        },
        {
          taskTitle: "Language Support for Workshop",
          time: "Today 02:00 PM",
          taskNumber: 2,
          totalEvents: 5,
          priority: "Low",
          priorityLabel: "Low",
          completed: false,
        },
      ],
    },
    {
      groupTitle: "NPO 03 Tasks",
      tasks: [
        {
          taskTitle: "Finalize Budget Proposal",
          time: "Tomorrow 10:00 AM",
          taskNumber: 1,
          totalEvents: 3,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: false,
        },
        {
          taskTitle: "Prepare Presentation for Client",
          time: "Tomorrow 01:00 PM",
          taskNumber: 1,
          totalEvents: 2,
          priority: "High",
          priorityLabel: "High",
          completed: false,
        },
        {
          taskTitle: "Review Contract Details",
          time: "Tomorrow 04:00 PM",
          taskNumber: 1,
          totalEvents: 1,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: true,
        },
      ],
    },
    {
      groupTitle: "NPO 04 Tasks",
      tasks: [
        {
          taskTitle: "Finalize Budget Proposal",
          time: "Tomorrow 10:00 AM",
          taskNumber: 1,
          totalEvents: 3,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: false,
        },
        {
          taskTitle: "Prepare Presentation for Client",
          time: "Tomorrow 01:00 PM",
          taskNumber: 1,
          totalEvents: 2,
          priority: "High",
          priorityLabel: "High",
          completed: false,
        },
        {
          taskTitle: "Review Contract Details",
          time: "Tomorrow 04:00 PM",
          taskNumber: 1,
          totalEvents: 1,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: true,
        },
      ],
    },
    {
      groupTitle: "NPO 05 Tasks",
      tasks: [
        {
          taskTitle: "Finalize Budget Proposal",
          time: "Tomorrow 10:00 AM",
          taskNumber: 1,
          totalEvents: 3,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: false,
        },
        {
          taskTitle: "Prepare Presentation for Client",
          time: "Tomorrow 01:00 PM",
          taskNumber: 1,
          totalEvents: 2,
          priority: "High",
          priorityLabel: "High",
          completed: false,
        },
        {
          taskTitle: "Review Contract Details",
          time: "Tomorrow 04:00 PM",
          taskNumber: 1,
          totalEvents: 1,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: true,
        },
      ],
    },
    {
      groupTitle: "NPO 06 Tasks",
      tasks: [
        {
          taskTitle: "Finalize Budget Proposal",
          time: "Tomorrow 10:00 AM",
          taskNumber: 1,
          totalEvents: 3,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: false,
        },
        {
          taskTitle: "Prepare Presentation for Client",
          time: "Tomorrow 01:00 PM",
          taskNumber: 1,
          totalEvents: 2,
          priority: "High",
          priorityLabel: "High",
          completed: false,
        },
        {
          taskTitle: "Review Contract Details",
          time: "Tomorrow 04:00 PM",
          taskNumber: 1,
          totalEvents: 1,
          priority: "Medium",
          priorityLabel: "Medium",
          completed: true,
        },
      ],
    },
    // Add more task groups as needed
  ];

  export default TaskData;